AWSTemplateFormatVersion: 2010-09-09
Description: |
  Fedora CoreOS Podman Builder Template

Parameters:
  VpcId:
    Type: String
  SubnetId:
    Type: String
  AllowedCidr:
    Type: String
  InstanceType:
    Type: String
  InstanceVolumeSize:
    Type: Number
  AMI:
    Type: "AWS::EC2::Image::Id"
  SshPubkeyName:
    Type: String

Resources:
  FedoraCoreOsSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH from admin containers"
      SecurityGroupIngress:
      - CidrIp: !Ref AllowedCidr
        IpProtocol: "tcp"
        FromPort: 22
        ToPort: 22
      VpcId: !Ref VpcId

  FedoraCoreOsInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: true
          VolumeSize: !Ref InstanceVolumeSize
      ImageId: !Ref AMI
      InstanceInitiatedShutdownBehavior: "terminate"
      InstanceType: !Ref InstanceType
      KeyName: !Ref SshPubkeyName
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: "0"
        GroupSet: 
        - !Ref FedoraCoreOsSg
        SubnetId: !Ref SubnetId
        DeleteOnTermination: true

Outputs:
  FedoraCoreOsInstance:
    Value: !GetAtt FedoraCoreOsInstance.PrivateIp